### ISSUE TITLE
General Representation of Cognate Sets (including partial cognacy)

### ISSUE THREAD

**Issue by LinguList** [glottobank/cldf#11]
the more I think about it and the more I talk about it with colleagues, it becomes evident that cognacy needs to expanded by the aspect of partial cognacy. In Indo-European, we have only spurious accounts, but in Tukano, Sino-Tibetan, and many other families, compounds are not just some little noise but constitute the basis of the lexical structure of the languages (30% in the nouns of Chinese dialects, but also pervasive in other families, like Tupi-Guarani).

Now, for partial cognacy, there is a straightforward representation. If we have words like "she-goat" and "he-goat", we can assign two IDs, that would render the stuff as "1 2" and "1 3". Note that we have cases in which we have the opposite order in the same language family, that is, we have "she-goat" in langauge A and "he-goat" in language B. Here, we would write "1 2" and "2 1". Note also that we _need_ to keep the information in one cell, since we want to store the order of the elements, and keep track of it for the alignmetns, which ideally would only be made for identical parts of the compounds. So we would have one alignment for cogid 1 and one for cogid 2, etc. In a file, we could represent this in a column by keeping the order of the original tokens, but adding a separator for morphemes:

``` text

TOKENS         COGID  ALIGNMENT           
sh e + g oa t       1 2         sh e + g oa t
h e + g oa t         1 3         h e + g oa t
g oa t + h e         3 1         g oa t + h e
```

So the alignment is no longer immediately visible when looking at the text-file, but automatically accessible and it can be displayed with tools that offer the service of comparing the cogid column with the column of segments (TOKENS). We loose transparency for those who want to read text-files, but we gain power for representing cognacy truthfully.

Furthermore, the format is consistent with unique-ID representations of cognacy:
- in a strict version, we require _identity_ of compound structure, which is nothing else than a check for identical strings in the cogid-representation which gives multiple numerical IDs in one cell separated by a space.
- in a loose version, we can make a connected component analysis of the underlying network and label the respective items as cognate, which share direct or indirect links with other items

My most recent idea was, that this should essentially be the basis, since it is so frequent in many language families, and also useful where it is less frequent (but never underestimate the degree of partial cognacy, also for IE languages, once you start being strict with morphemes!). And since those datasets where partial cognacy doesn't play a role would still simply show one ID for a cognate set, it would be largely consistent with the rest. 

But in danger of repeating myself here: we cannot ignore the problem of handling partial cognates. They are just too massively present in too many languages, and can also soon be fully handled by automatic cognate detection algorithms (provided, morpheme boundaries are known: I have recent highly promising results for lingpy).

**Comment by xrotwang** [comment]
How does this idea work with different cognacy types? Would the description of the cognacy types be something that has to be done per morpheme as well (I guess so)? So basically, the more information we want to attach to a particular cognacy judgement, the more unwieldy your approach gets. The alternative could be as follows: Make morphemes first class objects of analysis when it comes to cognacy. Of course this approach poses a couple of problems, too:
- How to markup constitutent morphemes in words? Can we rely on simple string identity? Probaby not - so morphemes need unique identifiers, too.
- Can legacy data be converted (automatically) to this finer type of analysis? Maybe by treating each word as a single morpheme first?

**Comment by LinguList** [comment]
well, I think that the major different cognacy types can actually be derived from this annotation, provided we have morpheme segmentation explicitly encoded in our unified phonetic transcription of the words and we encode regardless of semantics, we can derive swadesh cognacy, etc., based on either connected components of the underlying cognate morpheme network, or by just looking for identical matches.

Regarding the markup, I don't see a problem, but maybe I don't understand your concerns correctly. We only need to decide for a morpheme segmentizer that is used in addition to space segmentation in the unified phonetic transcription (the "TOKENS" column in lingpy).

Regarding legacy data: no, since we don't have morpheme boundaries marked here. But we could do it in parts, since, parts of the data shows word segmentation (which is also to be treated as partial cognacy).

But our general problem with legacy data is that this data is not in transcription, so we can't use it for this purpose anyway, but we would probably need the transcription to really deal with it.

Now that you mentioned the legacy data, I guess that it's probably not possible to take the partial cognate encoding as a basis, but just as one specific type. Yet that this type will be needed and useful, since there are datasets which will need a more finegrained encoding and people are currently working on language families which show these problems.

**Comment by LinguList** [comment]
One more point regarding legacy data: the current practice in ABVD and IELex is that a word that is partially cognate is assigned two cognate IDs. These cases are minimal, since compounding is not that big a problem in IE (although it is a problem in AN), but this is actually the exact encoding which I would propose, namely assigning 2 ids for words with two morphemes, but keeping the order of IDs to be able to trace back to the original word.

Compare "husband" in IELex, for example:

* http://ielex.mpi.nl/meaning/husband/languagelist/all/

which is given cognate classes "H, (O)", which means, one part is inherited ("House", and one is borrowed ("bond")). This is of course, a strange judgment, to have a half-borrowed word, but the double-assignment would actually be the encoding I propose for partial cognacy.

**Comment by LinguList** [comment]
So what the double-encoding basically means: also legacy data has the multiple assignment of words to different cognate sets, but the partial cognacy approach would make it more strict. And since the partial approach would also allow to only use one cognate identifier, this means that it is completely compatible with the other approach and in most cases, especially older datasets, there won't be multiple cognate sets assigned to the same word, but we should cover the possibility and if we do so, we should keep the order and link it to the morpheme structure (since otherwise we loose important information).

I am almost finished with creating a sample dataset of 18 Chinese dialects in which this cognate encoding is used.

**Comment by cormacanderson** [comment]
This is quite consistent with what we have planned for cobl.info, which is the new name for the successor of ielex. Have you a suggestion to deal with this monstrosity though @LinguList? http://www.cobl.info/cognate/2664/

**Comment by LinguList** [comment]
It will be difficult, and with people working on SEA and my on work on
Bai and Chinese, where I created first testset of partial cognates, I
realized that language-internal cognacy (morpheme analysis) is
potentially even more important as a first step. The reason is here in
SEA languages that they show a huge amount of recurring morphemes
already in basic vocabulary (bark == tree-sking, fingernail = hand-claw,
etc.).

But this illustrates only once more why we need this "monstrosity". And
for computational purposes, it is not difficult to either break it down
following some criterion (root-cognacy, strict cognacy), or to use
better models which account for these cases.

**Comment by LinguList** [comment]
Just wanted to add that the proposed format for partial cognates is now fully supported and working well in the EDICTOR tool for the manual editing of etymological data (http://edictor.digling.org) and also in LingPy (http://lingpy.org). 

That means essentially, that a dataset that passes partial cognates along with morpheme separation can be created, aligned, and evaluated. The essential part is the order of partial cognate identifiers which should reflect the order of morphemes. Once this is given, the data can be regularly and easily parsed. The edictor now even supports the annotation of partial cognates along with alignments in this format (as a new convention, I started to uses "0" as a cognate identifier that is left unassigned, which is useful for large amounts of data).

![bildschirmfoto_2016-03-30_13-29-12](https://cloud.githubusercontent.com/assets/2916210/14141440/3d282a04-f67f-11e5-9fa3-7bb0082908bf.png)
