### ISSUE TITLE
Provide an RDF vocabulary for CLDF properties

### ISSUE THREAD

**Issue by xrotwang** [glottobank/cldf#14]
To make it possible to annotate columns in CLDF data files unambiguously, we should provide an RDF vocabulary (along the lines of the [WGS84 example](https://www.w3.org/2003/01/geo/wgs84_pos)) defining properties which can be used as `propertyUrl` annotations in the metadata file.

This should include:
- http://cldf.clld.org/terms#glottocode
- http://cldf.clld.org/terms#iso-639-3
- http://cldf.clld.org/terms#concepticon-conceptset

**Comment by xrotwang** [comment]
The CLDF ontology should also include all identifiers used as values of `dc:type` properties, to specify `TableGroup`s and `Table`s which are recognized by CLDF.

**Comment by LinguList** [comment]
Allright, having closed #23, I suppose I should first remove what I added as markdown so far, and instead paste these things here? I also added some definitions, which seem like they'll come in handy, right? Do you, @xrotwang, prefer to have those things collected in the issue text, or is there a tabular format we could use for this?

**Comment by xrotwang** [comment]
We can start out with a table, I guess, and convert that to RDFS after some iterations. The "real" schema should live in the `gh-pages` branch, so that it is retrievable under `http://cldf.clld.org/terms`.

**Comment by LinguList** [comment]
Here is the data in the markdown-texts in CSV format. Can I leave it to you, @xrotwang, to upload it and expand it with the other terms, so that it is most straightforward to be integrated? 

[ontology.csv.txt](https://github.com/glottobank/cldf/files/1135263/ontology.csv.txt)

With this, the markdown folder ontology/*.md can also be deleted.

**Comment by xrotwang** [comment]
ok. will do.

**Comment by xrotwang** [comment]
@LinguList I put a preliminary version of the ontology up: http://cldf.clld.org/terms.rdf
We may want to tweak the xsl stylesheet which renders the RDF+XML as XHTML a bit to be more in line with the look and feel of the site ...
