### ISSUE TITLE
Specs need copyediting

### ISSUE THREAD

**Issue by Anaphory** [glottobank/cldf#17]
The specs contain several inconsistencies and apparent mistakes.

 - [ ] You specify nowhere what columns are required generically (Word lists have 4, but readme states “While the file may contain any number of columns”, while implicitly also making at least `ID` and `Language_ID` required)
 - [ ] There are half sentences: “Value: the word form, the main value, for the given language and the given concept (may have different degrees of ” (wordlist.md) – I think I saw another one, but can't retrace it right now.
 - [ ] structure_dataset.md has a word list example even though it speaks of “(often typological)” values, and the description on multi-dimensional features is very short

**Comment by xrotwang** [comment]
Thanks for these. I guess the main problem for CLDF at the moment is a missing schedule, i.e. everything is still in flux, and it is not entirely clear, when/how to cut the next release of the spec. Most work has been going on in the area of lexical data, but we just started discussing including aspects of dictionary-like data.

In any case, pilot apps like BEASTling should always have a say in what's needed and when, even if this requires more fine-grained releases.
