### ISSUE TITLE
How to handle partial cognate sets and cognate sets with alignments in general?

### ISSUE THREAD

**Issue by LinguList** [glottobank/cldf#20]
In `lexibank`, we have an extra file for cognate sets, with foreign keys (`Word_ID`). It seems like this can be specified in a straightforward way in CSV metadata. However, there are a few open questions:

1. we put cognate sets in an extra file to be able to handle different sources for cognate sets (e.g., one automatic version vs. one non-automatic version, which would be two extra columns in a flat csv in LingPy-format), but this somehow feels strange, as we would have the potential to assign one word to multiple cognate sets, but we would only allow this if the source is the same? Somehow, too much depends on the source as being the discriminating factor here, as with two different series of cognate judgments in one file, the only way to distinguish cognate sets would be to look at the source when evaluating and hoping that no word_id with identical source is assigned to multiple cognate sets (which would be the fuzzy annotation which is often used in ABVD and difficult to interpret)

2. in partial cognates, we assign one word form to multiple cognate sets, and the order is important, so in principle, we could either put one word_id in multiple rows, one for each partial cognate set, but we would have to report the index, or we accept that the morpheme structure of the "Segments" follows the order of the list of cognate-identifiers in the partial cognate set (which is space-separated).

Apart from the fact that I'd like to preserve some base-functionality to re-use the columns in flat csv files, if cognate sets do not require specific source annotation, it seems we need to add at least a Cognate_Set_Type column indicating whether a cognate set is a) fuzzy (ABVD-style, assigning one word ID to multiple cognate sets), b) unique, or c) partial.

But I'm having some trouble in making this a clear-cut example now that would reflect all things neatly, specifically, since the fuzzy, unique, partial distinction would require that based on that distinction the content of the field Cognate_Set changes (string vs. list, or integer vs. list in case of LingPy/EDICTOR).

**Comment by xrotwang** [comment]
ad 1) I think my preferred solution for this problem would be to consider different cognate judgements for the same words a reason to split a dataset into multiple CLDF (and potentially also lexibank) datasets. Somewhere in the lexibank docs we say something like "datasets must be homogeneous enough", and I'd argue this would be violated if you cannot reasonably analyze the dataset as a whole, but pretty much always have choose a subset.

Isn't this why we have the concept of derived datasets in lexibank?

**Comment by xrotwang** [comment]
ad 2) relying on row order in a cognates file to figure out which parts of a word gave rise to a certain cognacy judgement seems very error prone. Couldn't we introduce some sort of notation inspired by python's slices, e.g. `[2:5]`, which would translate to a slice of segments, and add this as additional column?

**Comment by LinguList** [comment]
1) the problem here is that we'll have many practical applications where we want to compare how well an algorithm performs against a gold standard, both in alignments and in cognate judgments. If we say, that this is somehow lingpy's custom-part of CLDF, this will also be fine, and LingPy (but also EDICTOR, where we have situations of two experts working on a dataset comparing their cognate judgments) could then expand CLDF, like adding custom names for computer-based cognate sets, and the like, right? In this case, we could even maintain my preferred flat file format, but allow to export it to pure cldf from lingpy.

2) we could use simple indices even, since a Segments instance is divided into Morphemes, and each partial cognate set will refer to only one morpheme. We could then add this information, the index, to the data, reserving either an empty string for non-partial cognate sets, or the index -1. In all cases, this would be consistent, as also the alignment could be parsed using the index. (I'll propose an example in a minute, where you can see this in the evaluation, how the alignments are assembled by using the index).

**Comment by xrotwang** [comment]
1. Yes, I think the right approach would be to have the application merge two or more CLDF datasets. Then the same application will be in control of the merge procedure as well as for distinguishing suitable subsets to compare. So basically CLDF would say: Here's several different things, but if you know how to compare, go ahead.

**Comment by xrotwang** [comment]
2. Is the assumption that partial cognacy judgements will always pertain to exactly one morpheme future-proof? If not, I'd go for slice notation right away. This would also give us a natural notation for non-partial cognacy: `[:]`.

**Comment by LinguList** [comment]
Well, in my opinion, it would be always one morpheme per cognate set, as neither algorithms nor annotation tools allow to assign partial cognacy to more than one morpheme. But this does of course not mean that we will always want to distinguish this later, especially if all languages share morpheme 1 and morpheme 2 exclusively in this order.

Another advantage of slice notation is that evaluation will not throw an error but simply yield an empty list, if the segments are too short or lack morpheme segmentation.

**Comment by xrotwang** [comment]
Ok, it just occurred to me that we may want to relate information to slices of segments in other contexts, too. So having a generic `Segments_slice` column which can be used together with a foreign key to a table with segmented lexical data would make sense anyway?

**Comment by LinguList** [comment]
Yes, I think this is a good idea!

**Comment by LinguList** [comment]
We can close this, once we have a pycldf that checks some kind of consistency. But in general, with #21, we have a first working example.

**Comment by LinguList** [comment]
And the working example is even published. Maybe we can close this completely, given that it is already in our ontology. For LingPy, we'll need parsers to read in cldf format, but that's not the issue at hand...
