### ISSUE TITLE
How to handle the CLDF ontology?

### ISSUE THREAD

**Issue by LinguList** [glottobank/cldf#23]
What I did now is just adding markdown-files with some automatically parsable structure (hopefully) to cldf in the folder `ontology`. The question is: are there any style guides for this kind of endeavour? We should define some relations, etc., of which I am aware, but I don't know how to code them in a most principled way, etc.

**Comment by xrotwang** [comment]
I think we should provide an ontology encoded as RDF Schema, similar to [this one](https://www.w3.org/2003/01/geo/wgs84_pos). See also #14

**Comment by xrotwang** [comment]
I'd propose we collect terms, concepts and properties which need identifiers within CLDF in #14.
