### ISSUE TITLE
Wordlist default CSV dialect unspecified

### ISSUE THREAD

**Issue by Anaphory** [glottobank/cldf#27]
The core standard says about Metadata-free conformance:
“To do so, the dataset must follow the default specification for the appropriate module regarding […] CSV dialect”, but the Wordlist module does no specify a default CSV dialect. Does that mean I should assume the dialect defaults given in http://w3c.github.io/csvw/metadata/#dialect-descriptions?

**Comment by xrotwang** [comment]
It actually does, see https://github.com/glottobank/cldf/blob/master/modules/Wordlist/Wordlist-metadata.json#L4-L6
But yes, missing attributes of the dialect spec default to the values given in the w3c spec.
