### ISSUE TITLE
Wordlist: Value with multiple Forms

### ISSUE THREAD

**Issue by Anaphory** [glottobank/cldf#28]
I am still somewhat confused what to make of multiple comma-separated forms in the word list Value column. Let's say my source says

> [de] Uncle: Onkel, Ohm/Oheim

What would be the natural way to put an entry like that in CLDF, where some forms are obvious variants of each other and other forms are not obviously related?

(1)
> ID,Language_ID,Parameter_ID,Value,Form
> 1,stan1295,1327,"Onkel,Ohm,Oheim",Onkel
> 1,stan1295,1327,"Onkel,Ohm,Oheim",Ohm
> 1,stan1295,1327,"Onkel,Ohm,Oheim",Oheim

(2)
> ID,Language_ID,Parameter_ID,Value,Form
> 1,stan1295,1327,"Onkel,Ohm,Oheim",Onkel
> 2,stan1295,1327,"Onkel,Ohm,Oheim",Ohm
> 3,stan1295,1327,"Onkel,Ohm,Oheim",Oheim

(3)
> ID,Language_ID,Parameter_ID,Value,Form
> 1,stan1295,1327,"Onkel",Onkel
> 2,stan1295,1327,"Ohm,Oheim",Ohm
> 2,stan1295,1327,"Ohm,Oheim",Oheim

(4)
> ID,Language_ID,Parameter_ID,Value,Form
> 1,stan1295,1327,"Onkel",Onkel
> 2,stan1295,1327,"Ohm,Oheim",Ohm
> 3,stan1295,1327,"Ohm,Oheim",Oheim

(5) Something else?

**Comment by xrotwang** [comment]
ID must uniquely identify a row in the CSV file - not a row in the source table. So this rules out (1) and (3). Given the distinction in the source, I'd say (4) conveys best what is given.

**Comment by Anaphory** [comment]
Excellent, that's what I thought would make sense, but it wasn't clear to me.

**Comment by xrotwang** [comment]
But of course you could add additional info, or maybe even create a custom self-referential foreign key relation, specifying "Oheim" as spelling variant of "Ohm".

**Comment by LinguList** [comment]
In many cases, however, we cannot tell what is a variant of another or what are truly different words with different histories. My practice in datasets which I am not willing to analyze completely, and also our current practice in lexibank is to select the first form (if the original data does not know better). This is transparent, insofar as we derive the form from the value by defining a splitter for each dataset. In other cases, where one has variants, but they are not really important, I tend to add them to an additional column called "variants". This is also what linguists would do if they write a dictionary.

**Comment by thiagochacon** [comment]
I would think we should have a way to preserve the source information when it provides what kind of variant a form is: orthographic, phonemic representation, morphological, etc.


-------- Mensagem original --------
De: Johann-Mattis List <notifications@github.com>
Data: 06/08/2017 08:44 (GMT-03:00)
Para: glottobank/cldf <cldf@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [glottobank/cldf] Wordlist: Value with multiple Forms (#28)


In many cases, however, we cannot tell what is a variant of another or what are truly different words with different histories. My practice in datasets which I am not willing to analyze completely, and also our current practice in lexibank is to select the first form (if the original data does not know better). This is transparent, insofar as we derive the form from the value by defining a splitter for each dataset. In other cases, where one has variants, but they are not really important, I tend to add them to an additional column called "variants". This is also what linguists would do if they write a dictionary.
