### ISSUE TITLE
Column with unset data type

### ISSUE THREAD

**Issue by Anaphory** [glottobank/cldf#43]
I noticed that I accidentally created a table without specifying the `datatype` for some column.
Is that valid?

CLDF does not say anything, `cldf validate` lets it pass, but `pycldf.db` assumes that `column.datatype.base` is defined.

**Comment by xrotwang** [comment]
The datatype defaults to `string` - which is what you would expect for stuff that's read from a text file.

**Comment by Anaphory** [comment]
So, is there a need to raise an issue for `pycldf.db`?

**Comment by xrotwang** [comment]
Ah, sorry. No, `pycldf.db` should also default to `TEXT`.

**Comment by xrotwang** [comment]
Moved to https://github.com/glottobank/pycldf/issues/43
