### ISSUE TITLE
check to which degree phoible describes existing datasets

### ISSUE THREAD

**Issue by LinguList** [glottobank/cldf#8]
With the [benchmark database of phonetic alignments](http://alignments.lingpy.org) and the [benchmark data for cognate detection](http://sequencecomparison.github.io) there are two large datasets which provide phonetically segmented data. The question, also with respect to the idea that we might link individual sounds to phoible, is now: to which degree covers phoible the sounds in those and maybe also other datasets?

By carrying out this small analysis, we would have a better estimate on how difficult it is to use things like phoible for reference in our future endeavours (or whether we need to come up with an alternative system of tracking sounds ourself, that, eventually, may built upon phoible).

One further important point on mapping things to phoible is, that we should not underestimate the problems of IPA-variation. IPA has, for example, versions for /ts/ both as single character, as two characters, and as two characters with a combining character. There are also two versions of g, different ways of describing tone, and all other kinds of problems. Now, in order to use phoible as a reference, we need to come up with a mapping of all these variants to the respective phoible symbols, and preferably also with a mapping of non-standard IPA variants, like /th/ for aspirated t, which we will frequently encounter in the lexical data. This could turn out to be quite tedious, but also useful. Anyway, the starting point is to check to which degree we find agreement between the above-mentioned databases and phoible, but potentially also Paul's sound comparison databases.

**Comment by xrotwang** [comment]
Good idea. I think what makes PHOIBLE so useful is exactly the fact that it tries to remove the ambiguities still inherent in IPA. While I do not have much hope of fully automatic conversion of messy data like IDS to proper (PHOIBLE-)IPA, I at least think, PHOIBLE can provide an important piece for quality assessment - in some sense its a benchmark database as well.

**Comment by LinguList** [comment]
Update on this matter: I just run a test (code is at glottobank/phonobank-data/tests/phoible-integration) along with all datasets (alignmetns and wordlists).

The results are [here](https://github.com/glottobank/phonobank-data/blob/master/tests/phoible-integration/missing_segments.tsv). In brief: 578 elements do not occur in Phoible, while 360 occur. Generally the dataset is quite huge with a total of 74562 words. 

Inspecting problematic elements you can find in the file mentioned above, we see that most of them are vowels (almost all diphtongs). Tones are encoded differently, so here one might adjust (though I hate the tone marks used in phoible). The consonants, there are 128, are often due to the variants we discussed, maybe all of them, but this needs a closer inspection.

So, if we put the vowels at the side or treat diphtongs as consisting of single vowels, we might actually come to some raw phobile coverage. One might even use the lingpy-sound-class alphabet to create some mapping of data like the one I tested here to "phoible". In the end, all can be treated as some specific sound class.

**Comment by LinguList** [comment]
One more thing: In LingPy, we have a default character that shows that a given sound cannot be mapped to a sound-class alphabet (when there are errors). The same could, of course, be done with a phoible mapping...

**Comment by LinguList** [comment]
An update: many of the cases which do not map are errors. But not all. Phoible does not, for example, know the diphtong əʊ which is often used in transcriptions for things like English "swallow" or the like. Now, how do we deal with these cases? And there are more!

```tsv
SEGMENT	FREQUENCY	CLASS
əʊ	10	V
auː	7	V
eiː	6	V
ouː	6	V
ɛˀ	5	V
øyː	3	V
yˀ	2	V
ɔˀ	2	V
ɒˀ	2	V
øːʌ	2	V
æˀ	1	V
øˀ	1	V
ɶ	1	V
aiː	1	V
ɶˀ	1	V
ʏː	1	V
ɑˀ	1	V
œˀ	1	V
ðˀ	4	C
ʁˀ	4	C
gː	2	C
b̥	2	C
d̥	1	C
```

Note that not all of these are unmappable, but some are definitely. 

My suggestion would be to follow the lingpy tactics:

1. try to identify segment (include down-mappings, like all variants of ts, and the like)
2. if you still can't identify a segment, try the first letter of the segment (token[0]). 
3. if you still can't identify this, mark it as unmappable.

We can further adopt the strategy for diphtongs:

* if the diphtong can be segmented into values occuring both in Phoible, split it.

At some point, we might want to involve the phoneticians among us. It seems still strange to me, that certain sounds do not occur in Phoible...

**Comment by xrotwang** [comment]
@LinguList I guess, I am more interested in figuring out whether PHOIBLE can be used for quality assessment on a per wordlist of per language basis. I.e. if all segments used in word forms of a wordlist are found in the PHOIBLE segment inventory for the respective language, I could be quite confident, that the forms are transcribed in IPA and thus comparable to other datasets. E.g. some of the IDS wordlists contain unicode glyphs from cyrillic code blocks which look like IPA glyphs. Such problems could be detected when cross-checking with PHOIBLE, I guess, unless the rate of false positives is too high, because the PHOIBLE inventory doesn't really describe the reality of these wordlists.

**Comment by LinguList** [comment]
Okay, but in order to proceed, you will anyway need a mapping of those IPA-internal ambiguities to the phoible version, not? And since phoible itself doesn't seem to transcribe (yet) all possibilities, we need strategies to check, for example, for certain diphtongs. Also, accent marks need to be stripped off, as well as other marks which are relevent for a word transcription but not for an inventory transcription.

**Comment by xrotwang** [comment]
Yes, such a mapping or normalization would be great to have. I don't think PHOIBLE aims to catalog all possibilities, but only whatever has actually been put into phoneme inventories by linguists. So I would find it more tractable to work on a wordlist-by-wordlist basis and aggregate common pitfalls into such a normalization script, rather than trying to code up all of the [PHOIBLE conventions](http://phoible.github.io/conventions/) in one go - just to find out, the data we deal with isn't any IPA et all, but could be made so with a couple of hacks.

**Comment by LinguList** [comment]
Yes, I agree. I already collected a few of them common pitfalls in the past.

I don't know, whether the way I program it is useful, but I have one mapper that maps IPA to IPA.phoible, like this one:

```python
mapper = {
        'p͡f' : 'pf',
        'ʧ' : 'tʃ',
        'g' : 'ɡ',
        'ḷ' : 'l̩',
        'ṇ' : 'n̩',
        'ʦ' : 'ts',
        'ʤ' : 'dʒ',
        'eã' : ['e', 'ã'],
        'eɑ̃' : ['e', 'ɑ̃'],
        'eːaː' : ['eː','aː'],
        'ya' : ['y','a'],
        'ɶː' : 'œː',
        'ɪə' : ['ɪ','ə'],
        'ʊə' : ['ʊ','ə'],
        'gː' : 'ɡː',
        'ɶ' : 'œ',
        'b̥' : 'p',
        'd̥' : 'd'
        }
```

And I also have one "cleaner", which cleans up the code by general replacement patterns which one can just apply to any string, since they are n to n:

```python
# tuple[0] == source, tuple[1] == target
cleaner = [
        (':', 'ː'),
        ('g','ɡ')
        ]
```

I've started testing this on my wordlists with segmentation, and I can reach almost full coverage, and the process of adjusting is actually not too tedious. It also helps to clean one's own data.

Here's the current status, btw: glottobank/phonobank-data/tests/phoible-integration/

There are also all the segmented wordlists I mentioned before.

**Comment by xrotwang** [comment]
@LinguList Yes, I would hope that this approach works at least 90% of the time.

**Comment by LinguList** [comment]
I'll report on this when I prepare the data for lexibank. I then suppose I add an additional layer of segmentation:

* orthography
* ipa (as received, without segmentation)
* tokens (lingpy-tokens, manually adjusted, which is needed at times)
* phoible

Having these three stages seems important to trace where the data came from in the end. Would you agree?

**Comment by xrotwang** [comment]
Yes, that's already way ahead of most of the data we will have to integrate, but should define the level of accuracy we want to get at.

**Comment by LinguList** [comment]
Okay, I started working on a function that takes an "ipa" string in some raw form without nasty brackets as input and converts it to phoible (see phonobank-data/tests/phoible-integration/utils.py). This function normalizes already some great deal. I adopted the following conventions (to be discussed, probably, in more detail:

1. when there are unrecognized diphtongs, check for their constituents, mark this by adding a dot-character between the vowels.

Example:
```python
>>> tokens2phoible('n æ r əʊ')
['n', 'æ', 'r', 'ə.ʊ']
```
2. add a question mark before any segment which is not mappable to phoible, example:
```python
>>> tokens2phoible('blu:twurSt')
['b', 'l', 'uː', 't', 'w', 'u', 'r', '?S', 't']
```
3. Do this also for the segments of a diphtong, but then only for the vowel in the diphtong set:
```python
>>> tokens2phoible("'b l u: t w uA r s t'")
['b', 'l', 'uː', 't', 'w', 'u.?A', 'r', 's', 't']
```
There are more small modifications which are included, like representing geminates with a length marker rather than double markers, ignoring accents, etc. The function is a bit complicated, but it should provide some help, and when adding more and more data, we may hopefully increase the accuracy by adding more mappings, etc.

**Comment by LinguList** [comment]
An update: The function works fine so far, but there will be definite problems with phoibles coverage: when testing for germanic and indo-euroepan data, it seems to work well, but for SEA data, it shows a big gap in phoible: first, the actual values are largely erroneous (even Manarin Chinese is assigned wrong tones!), secondly, there are many missing sounds, like, for example aspirated fricatives, and the like. So at some point, we will need to contact Steven and give him the data to be appended to phoible, since there are quite a few sounds missing. Steven may actually be happy about this. But how should we proceed in the mean-time? Should I mark those cases where there is an ambiguous gap in phoible?

BTW: this also answer the question of mapping data to one language explicitly in phoible: we can't do this, since the transcriptions systems vary hugely, and phoible often has some in my opinion not very reliable source (at least for the languages I have worked on so far).

**Comment by xrotwang** [comment]
Well, the only way to get data into PHOIBLE is by publishing a phoneme inventory for a language, I guess. AFAIK PHOIBLE doesn't aim at being a catalog of the world's sounds (at least currently). So I would suggest to compile a blacklist of languages for which mapping to PHOIBLE doesn't make sense. Maybe this list could be of interest for Steve, because it may overlap with languages not yet in PHOIBLE, and help prioritise aqcuisition of new inventories.

If we can only map to the set of all segments in PHOIBLE and not to exactly one inventory, this may still be worthwhile in terms of IPA normalization, but it would lose quite a bit of its appeal. (Although, I think, that was to be expected, considering the ideosyncratic transcription systems.)

**Comment by LinguList** [comment]
Well, in that case, I suppose we take phoible as starting point and reference it wherever possible, and start making our catalogue of sounds in the world ourselves. If glottobank really aims at making a difference, and we plan to assemble high-quality data in the future, then we should do this anyway. 

Quite a few languages not in phoible can be added from data I have on SEA languages. Here, transcriptions are usually from sources which phoible did not yet find time to digitize, I guess. When preparing the data, I'd suggest to follow phoible's normalization as good as possible, but to eventually mark new sounds to be given to Steven along with the language's phoneme inventories at some point. I thus make up an additional list now with sounds unambiguously missing in phoible, given a certain language. In the utils.py conversion, I'll mark sounds currently not in phoible with '⁽⁺⁾' after the segment (should be clear that this has no phonetic value, and in automatic analyses, it can easily be ignored). In this way, one can directly see for each wordlist, to which degree it is normalized regarding it's ipa, and one can see which of the phoneme inventory (which we may display additionally in lexibank, along with links to phoible), is not covered in phoible. 

Does that sound like a useful plan for ipa-normalization? I staretd testing on my data, and most of the time, the ambiguous elements shrink down to a few, and the normalization is also quite useful. I even think of including this at some stage into lingpy. So far, I thought IPA normalization was too tedious, but maybe it's time to try and tackle it, albeit in a pragmatic way...

**Comment by xrotwang** [comment]
Sounds workable. Should we move this issue to phonobank, then?

**Comment by LinguList** [comment]
Yes, very good idea! This is definitely then to be handled as one of
PhonoBank's responsibilities.

**Comment by LinguList** [comment]
Okay, I don't know how to move issues on github, and there seems to be no real way to do it unless using some external apps. So I moved this issue to:

* https://github.com/glottobank/phonobank-data/issues/2

And I'm closing this one for the meantime.
